# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-14 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('full_name', models.CharField(default=None, max_length=50, null=True, verbose_name='full_name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('mobile', models.BigIntegerField(null=True, verbose_name='mobile')),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('otp', models.IntegerField(null=True, verbose_name='otp')),
            ],
            options={
                'db_table': 'appuser',
                'verbose_name': 'Application User',
                'verbose_name_plural': 'Application Users',
            },
        ),
    ]
