# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-22 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20170822_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='last_name',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='last_name'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='middle_name',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='middle_name'),
        ),
    ]
